export const photographers = [
    {
        name: "Myyeol ",
        username: "Dưới 1 năm kinh nghiệm",
        location: "TP Hồ Chí Minh",
        price: "300,000 VND / giờ",
        minHours: 2,
        bio: "Mình thích chụp ảnh và phong cách mình hướng đến là style nàng thơ và ngoại cảnh 🌸",
        images: [
            "/i1.webp",
            "/i2.webp",
            "/i3.webp",
            "/i4.webp",
            "/i5.webp",
            "/i6.webp",
            "/i7.webp",
        ],
        profilePicture: "/myyeol.webp",
    },
    {
        name: "Huy Bùi",
        username: " Đã có 1-3 năm kinh nghiệm",
        location: "Đà Nẵng",
        price: "400,000 VND / giờ",
        minHours: 2,
        bio: "mình có ước mơ chụp thật nhiều để rồi mình sẽ nâng cao dần trình độ và các khách hàng sẽ quay lại cùng mình trên con đường sắp tới.",
        images: [
            "e1.webp",
            "e2.webp",
            "e3.webp",
            "e4.webp",
            "e5.webp",
            "e6.webp",
            "e7.webp",
        ],
        profilePicture: "huybui.jpg",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
    {
        name: "Daniele Torella",
        username: "danieletorella",
        location: "Rome, Italy",
        price: "9 700 000 VND / hour",
        minHours: 2,
        bio: "Documenting exclusive weddings around the world through cinematic, elegant and timeless photographs. As seen in Vogue, ELLE & Vanity Fair.",
        images: [
            "a.webp",
            "b.jpg",
            "d.webp",
            "e.jpg",
            "e.jpg",
            "e.jpg",
            "e.jpg",
        ],
        profilePicture: "f.webp",
    },
];

export const major = [
    "Wedding",
    "Portrait",
    "Landscape",
    "Fashion",
    "Sports",
    "Wildlife",
    "Event",
    "Commercial",
    "Travel",
    "Documentary",
];

export const photos = Array.from({ length: 28 }, (_, index) => ({
    src: `cat${Math.floor(Math.random() * 4) + 1}.jpg`,
    bookmark: ["green", "red"].filter(() => Math.random() > 0.5),
    author: "dinhbang",
    likes: 12,
    comments: 54,
    saves: 12,
}));

export const photographerProfile = {
    img: "huybui.jpg",
    name: "Huy Bùi ",
    location: "Đà Nẵng ",
    userName: "Huy Bùi",
    description:
        "Mình có ước mơ chụp thật nhiều để rồi mình sẽ nâng cao dần trình độ và các khách hàng sẽ quay lại cùng mình trên con đường sắp tới.",
    joiningAt: "15/3/2024",
    language: "tiếng Ý, tiếng Anh, tiếng Tây Ban Nha",
    follower: 1113,
    phoneNumber: "0912341234",
    award: [
        "Nhiếp ảnh gia được yêu thích nhất tuần",
        "Top 3 trong hạng mục chụp ảnh cặp đôi của tháng",
    ],
    major: [
        { name: "đám cưới", price: 1000000 },
        { name: "cặp đôi", price: 2000000 },
        { name: "thai sản", price: 30000000 },
        { name: "gia đình", price: 4000000 },
    ],
    website: "bangdinh.com",
    price: [
        { name: "đám cưới", price: 1000000 },
        { name: "cặp đôi", price: 2000000 },
        { name: "thai sản", price: 30000000 },
        { name: "gia đình", price: 4000000 },
    ],
};
